# Name of the workflow
name: Run ETHOS.PeNALPS Tests
# Events that trigger the workflow
on:
  push:
    branches: main
  pull_request:
    branches: main
  # Allows to trigger the workflow manually
  workflow_dispatch:
    branches: main

jobs:
  # defines a job id 
  run_test_on_micromamba:
      # Defines a name for the job id
      name: Run windows test image
      runs-on: windows-2022
      defaults:
        # Define the shell to be used in the job
        run:
          shell: powershell
      steps:
        # Checkout the repository
        - name: Check out the repository to the runner
          uses: actions/checkout@v4
        - name: Setup Miniforge
          run: |
           curl.exe --output Miniconda3-py39_4.9.2-Windows-x86_64.exe --url https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Windows-x86_64.exe
           $minidir="$PWD\Miniconda3"
           echo $minidir
           mkdir $minidir
           Start-Process Miniconda3-py39_4.9.2-Windows-x86_64.exe -Wait -ArgumentList @('/S', '/InstallationType=JustMe', '/RegisterPython=1', '/D="$minidir"')
           echo "path to powershell script is"
           Join-Path $minidir -ChildPath "condabin" | Join-Path -ChildPath "shell" | Join-Path -ChildPath "conda-hook.ps1"
           echo $path
           $path
           echo "Powershell is activated"
           conda -V
           mamba -V
        # - name: miniforge
        #   run: setup_conda.bat
        # - name: miniforge
        #   run: |
        #    $directoryname = "MambaforgeDir"
        #    $filebase = Join-Path $PSScriptRoot $directoryname
        #    start /wait "" Miniforge.exe /InstallationType=JustMe /RegisterPython=1 /AddToPath=1 /S /D=$filebase
        - name: Show files
          run: tree /f
        
        # - name: Conda
        #   run: | 
        #     set path=%path%;"$PSScriptRoot$\Miniforge\script" 
        #     conda -V
        #     mamba -V
        # # - name: Mamba
        # #   run: mamba -V