# Name of the workflow
name: Run ETHOS.PeNALPS Tests
# Events that trigger the workflow
on:
  push:
    branches: main
  pull_request:
    branches: main
  # Allows to trigger the workflow manually
  workflow_dispatch:
    branches: main

jobs:
  # defines a job id 
  run_test_on_micromamba:
      # Defines a name for the job id
      name: Run windows test image
      runs-on: windows-2022
      defaults:
        # Define the shell to be used in the job
        run:
          shell: powershell
      steps:
        # Checkout the repository
        - name: Check out the repository to the runner
          uses: actions/checkout@v4
        # download miniforge
        - name: download miniforge
          run: curl.exe --output Miniforge.exe --url https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe -L
        # - name: Echo that workflow terminated
        #   run: echo "Download terminated"
        # - name: Show files
        #   run: tree /f
        # - name:  Install Miniforge
        #   run: | 
        #    start /wait "" %BUILD_ARTIFACTSTAGINGDIRECTORY%\Miniforge.exe /InstallationType=JustMe /RegisterPython=0 /S /D=C:\Miniforge
        # Checkout the repository

        # - name: Install winget
        #   uses: Cyberboss/install-winget@v1
        # - run: echo '${{ steps.stepid.outputs.winget-version }}'
        # - name: install miniforge
        #   run: winget install -e --id CondaForge.Miniforge3 --accept-source-agreements --accept-package-agreements
        - name: working directory
          run: Get-Location
        - name: working directory 2
          run: echo $PSScriptRoot
        - name: working directory 3
          run: |
            $directoryname = "MambaforgeDir"
            $filebase = Join-Path $PSScriptRoot $directoryname
            echo $filebase
        - name: miniforge
          run: start /wait "" Miniforge.exe /InstallationType=JustMe /RegisterPython=0 /S /D=%UserProfile%\Miniforge3
        # - name: miniforge
        #   run: |
        #    $directoryname = "MambaforgeDir"
        #    $filebase = Join-Path $PSScriptRoot $directoryname
        #    start /wait "" Miniforge.exe /InstallationType=JustMe /RegisterPython=1 /AddToPath=1 /S /D=$filebase
        - name: Show files
          run: tree /f
        
        - name: Conda
          run: | 
            set path=%path%;"$PSScriptRoot$\Miniforge\script" 
            conda -V
            mamba -V
        # - name: Mamba
        #   run: mamba -V