on:
  push:
    branches: main
  pull_request:
    branches: main
  # Allows to trigger the workflow manually
  workflow_dispatch:
    branches: main
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Some Examples for cron syntax
    # Schedules job at any point after 12 pm
    - cron:  '0 0 * * *'

jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge
          activate-environment: test_env
      - name: Run Fine test
        shell: pwsh
        run: |
          mamba install fine pytest
          pytest
        