on:
  push:
    branches: main
  pull_request:
    branches: main
  # Allows to trigger the workflow manually
  workflow_dispatch:
    branches: main
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Some Examples for cron syntax https://crontab.guru/examples.html
    # Schedules job at any point after 12 pm
    - cron:  '0 0 * * *'
    # Weekly after sunday
    # - cron: 0 0 * * 0

jobs:
  TestCombinedSingle:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - name: Checkout Fine
        uses: actions/checkout@v2
        with:
          repository: FZJ-IEK3-VSA/FINE
          path: './fine'  
      - name: Checkout geokit
        uses: actions/checkout@v2
        with:
          repository: FZJ-IEK3-VSA/geokit
          path: './geokit'
      - name: Checkout glaes
        uses: actions/checkout@v2
        with:
          repository: FZJ-IEK3-VSA/glaes
          path: './glaes'
      - name: Checkout Reskit
        uses: actions/checkout@v2
        with:
          repository: FZJ-IEK3-VSA/RESKit
          path: './reskit'      
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge
          activate-environment: test_env
      - name: Run tests
        shell: pwsh
        run: |
          ls
          echo "LS Done"
          mamba install fine geokit glaes reskit pytest
          echo "Installation done"
          conda list
          echo "libaries printed"
          echo "start pytest"
          pytest
          echo "Pytest done"
        